# Generated by Django 5.2.11 on 2026-02-19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_user_groups_alter_user_is_superuser_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="full_access_override",
            field=models.BooleanField(
                default=False,
                help_text="Grant full Pro features from admin regardless of subscription status.",
            ),
        ),
    ]
