# Generated by Codex on 2026-02-09
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Subscription",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("provider", models.CharField(choices=[("stripe", "Stripe"), ("razorpay", "Razorpay")], max_length=16)),
                ("status", models.CharField(choices=[("active", "Active"), ("past_due", "Past Due"), ("canceled", "Canceled")], max_length=16)),
                ("plan", models.CharField(default="pro", max_length=32)),
                ("provider_customer_id", models.CharField(blank=True, max_length=128)),
                ("provider_subscription_id", models.CharField(blank=True, max_length=128)),
                ("current_period_end", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
