# Generated by Django 5.2.11 on 2026-02-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("processing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="processingjob",
            name="progress",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="processingjob",
            name="stage",
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
